apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-grafana
  labels:
    name: pvc-grafana
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi