apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  labels: 
    run: prometheus
  name: pvc-prometheus
spec: 
  accessModes: 
    - ReadWriteOnce
  resources: 
    requests:
      storage: 2Gi