apiVersion: v1
kind: Service
metadata:
  name: prometheus-svc
  labels:
    run: prometheus
spec:
  selector:
    run: prometheus
  type: NodePort
  ports:
  - nodePort: 30008
    port: 9090
    targetPort: 9090
    name: prometheus-port
