apiVersion: v1
kind: Service
metadata:
    name: grafana-svc
    labels:
      run: grafana
spec:
    selector:
      run: grafana
    type: NodePort
    ports:
    - nodePort: 30009
      port: 3000
      targetPort: 3000
      name: grafana-port